### ISSUE TITLE
SqlException

### ISSUE THREAD

**Issue by YanYas** [MyCaffe/MyCaffe-Samples#1]
I have some difficulties getting the samples to work.

The first error I came across was this:

> Could not copy the file "C:\VLMyCaffe\MyCaffe-Samples-master\ImageClassification\ImageClassification\SqlServerTypes\x64\msvcr120.dll" because it was not found.	ImageClassification		

	
Image Classification sample requires MySQL. This is okay in my case because I've installed it previously, but it may come as a surprise to new users.
When I added them from elsewhere, it builds.

When I click the 'Simple Classification' button I get a message saying I must Export Images first. When I click it I get the following error:

> SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

As someone with little experience with SQL I find it a little overwhelming when I'm trying to follow how MyCaffe as a system is behaving in the assumption that the data is already inside it. The MySQL part somewhat interferes with that at the moment, and would appear to completely dependent upon MySQL being installed in order to do anything.

I feel that this example, while simple in terms of its result, means getting to grips with a few different ideas at once. 

Maybe the sql loading could be demonstrated separately from an in-memory version, so users can get into the meat of the layers/proto system a little easier without this additional technical overhead. I don't want to diminish its importance, since it will be essential for large datasets, but for learning the basics it over complicates the setup.

**Comment by YanYas** [comment]
The full txt output
[MyCaffeSqlOutput in full.txt](https://github.com/MyCaffe/MyCaffe-Samples/files/4165024/MyCaffeSqlOutput.in.full.txt)

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

Good points - we will add an export functionality to the MyCaffe Test Application that extracts the MNIST files into their image form.  Once you have placed the extracted MNIST images files into the \programdata\MyCaffe\test_data\mnist\testing and \programdata\MyCaffe\test_data\mnist\training directories, you can use the ImageClassificationBareBones sample without using SQL.

One note, MyCaffe uses Microsoft SQL or Microsoft SQL Express - not MySql.  Are you using MySql?

**Comment by ZoroDerVonCodier** [comment]
Hi @YanYas ,

We have updated the MyCaffe Test Application to now support both running the GYM (used by reinforcement learning sample) and now allows for exporting the MNIST data files into images without SQL.

To extract the MNIST data files, just run the MyCaffe Test Application (ignore the SQL errors and warnings), select the 'Database | Load MNIST...' menu and then make sure to check the 'Export to file only' option.  Running this then exports the files in the manner expected by the ImageClassificationBareBones sample.

The following samples can be run without SQL installed:

ImageClassificationBareBones (requires updated MyCaffe Test App)
BlobUsage
MemoryDataLayer
ReinforcementLearning (requires updated MyCaffe Test App)

And the following examples DO require Microsoft SQL or Microsoft SQL Express:

ImageClassification
OneShotLearning

Hope this helps!

**Comment by YanYas** [comment]
Thanks I'll check alittle later

**Comment by ZoroDerVonCodier** [comment]
@YanYas ,
We are closing this out for these are fixed in the new drop that we just released.
